apiVersion: v2
name: secuimage-backend
description: Deploys secuimage-backend
type: application
version: 2.0.3
appVersion: "2.8.3"
dependencies:
  - name: common
    version: 0.3.2
    repository: "https://coltonhughes.github.io/helm-charts"
