apiVersion: v2
name: sonarr
description: A Helm chart for running Sonarr on k8s
type: application
version: 1.1.3
appVersion: "3.0.10"

dependencies:
  - name: common
    version: 1.1.3
    repository: "file://../common"
