apiVersion: v2
name: sonarr
description: A Helm chart for running Sonarr on k8s
type: application
version: 2.0.2
appVersion: "3.0.10"
dependencies:
  - name: common
    version: 0.3.2
    repository: "file://../common"
