apiVersion: v2
name: overseerr
description: A Helm chart for running overseerr on k8s
type: application
version: 1.1.5
appVersion: "1.33.2"

dependencies:
  - name: common
    version: 1.1.5
    repository: "file://../common"
