apiVersion: v2
name: overseerr
description: A Helm chart for running overseerr on k8s
type: application
version: 2.0.3
appVersion: "1.33.2"
dependencies:
  - name: common
    version: 0.3.2
    repository: "https://coltonhughes.github.io/helm-charts"
