apiVersion: v2
name: sabnzbd
description: A Helm chart for running sabnzbd on k8s
type: application
version: 2.0.3
appVersion: "4.1.0"
dependencies:
  - name: common
    version: 0.3.2
    repository: "https://coltonhughes.github.io/helm-charts"
