apiVersion: v2
name: sabnzbd
description: A Helm chart for running sabnzbd on k8s
type: application
version: 2.0.4
appVersion: "4.1.0"
dependencies:
  - name: common
    version: 0.5.4
    repository: "https://coltonhughes.github.io/helm-charts"
