apiVersion: v2
name: sabnzbd
description: A Helm chart for running sabnzbd on k8s
type: application
version: 1.0.2
appVersion: "4.1.0"

dependencies:
  - name: common
    version: 1.0.2
    repository: "file://../common"
