apiVersion: v2
name: homepage
description: A Helm chart for running Homepage on k8s
type: application
version: 2.0.2
appVersion: "1.8.0"
dependencies:
  - name: common
    version: 0.5.5
    repository: "https://coltonhughes.github.io/helm-charts"
