apiVersion: v2
name: plex
description: A Helm chart for running plex on k8s
type: application
version: 1.2.0
appVersion: "1.32.8"

dependencies:
  - name: common
    version: 1.2.0
    repository: "file://../common"
