apiVersion: v2
name: plex
description: A Helm chart for running plex on k8s
type: application
version: 2.0.3
appVersion: "1.32.8"
dependencies:
  - name: common
    version: 0.3.2
    repository: "https://coltonhughes.github.io/helm-charts"
