apiVersion: v2
name: jackett
description: A Helm chart for running Jackett on k8s
type: application
version: 2.0.1
appVersion: "0.21.958"
dependencies:
  - name: common
    version: 0.3.1
    repository: "file://../common"
