apiVersion: v2
name: jackett
description: A Helm chart for running Jackett on k8s
type: application
version: 2.0.2
appVersion: "0.21.958"
dependencies:
  - name: common
    version: 0.3.2repository: "file://../common"
