apiVersion: v2
name: radarr
description: A Helm chart for running Radarr on k8s
type: application
version: 1.1.5
appVersion: "4.5.2"

dependencies:
  - name: common
    version: 1.1.4
    repository: "file://../common"
