apiVersion: v2
name: radarr
description: A Helm chart for running Radarr on k8s
type: application
version: 2.0.4
appVersion: "4.5.2"
dependencies:
  - name: common
    version: 0.5.4
    repository: "https://coltonhughes.github.io/helm-charts"
