apiVersion: v2
name: prowlarr
description: A Helm chart for running prowlarr on k8s
type: application
version: 1.1.5
appVersion: "1.8.1259"

dependencies:
  - name: common
    version: 1.1.4
    repository: "file://../common"
